// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFBWBm44T_Vkt7nVgodNGKbdtt-F6Obg4',
    appId: '1:249808151606:web:4f549a6de601127305a497',
    messagingSenderId: '249808151606',
    projectId: 'skillmatch-6dd45',
    authDomain: 'skillmatch-6dd45.firebaseapp.com',
    storageBucket: 'skillmatch-6dd45.firebasestorage.app',
    measurementId: 'G-6QPEHHJ2S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-sos1ZyoQUE_xFbK2_CgwYuQJuL96Bgk',
    appId: '1:249808151606:android:4c20320545948f5605a497',
    messagingSenderId: '249808151606',
    projectId: 'skillmatch-6dd45',
    storageBucket: 'skillmatch-6dd45.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjl8WawFAlp82lyWj47CcYzZbDmbfby3E',
    appId: '1:249808151606:ios:b145ab523673dd8b05a497',
    messagingSenderId: '249808151606',
    projectId: 'skillmatch-6dd45',
    storageBucket: 'skillmatch-6dd45.firebasestorage.app',
    iosBundleId: 'com.example.hand4hand',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjl8WawFAlp82lyWj47CcYzZbDmbfby3E',
    appId: '1:249808151606:ios:b145ab523673dd8b05a497',
    messagingSenderId: '249808151606',
    projectId: 'skillmatch-6dd45',
    storageBucket: 'skillmatch-6dd45.firebasestorage.app',
    iosBundleId: 'com.example.hand4hand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFBWBm44T_Vkt7nVgodNGKbdtt-F6Obg4',
    appId: '1:249808151606:web:5e0967ff8a31671d05a497',
    messagingSenderId: '249808151606',
    projectId: 'skillmatch-6dd45',
    authDomain: 'skillmatch-6dd45.firebaseapp.com',
    storageBucket: 'skillmatch-6dd45.firebasestorage.app',
    measurementId: 'G-4VDBRG0HS1',
  );
}
